In [1]:
import pandas as pd
import numpy as np

In [2]:
# definir arquivo Pickle de entrada
arquivo = 'afastamentos-nomes-sexo-preparado.pkl.bz2'
#arquivo = 'cadastro-nomes-sexo-preparado.pkl.bz2'
#arquivo = 'extra/nome_sexo_pf05.csv'

In [3]:
df = pd.read_pickle(arquivo)
df.head()

SEXO  QTDE  L0  L1  L2  L3  L4  L5  L6  L7  L8  L9  L10  L11  L12  \
NOME                                                                           
MARIA         0   121   1   9  18   1  13   0   0   0   0   0    0    0    0   
JOSE          1   206   5  19  15  10   0   0   0   0   0   0    0    0    0   
ANTONIO       1   233  15   9  14  15  20  14   1   0   0   0    0    0    0   
FRANCISCO     1   246  15   3  19   9   3  14   1  18   6   0    0    0    0   
JOAO          1   225  15   1  15  10   0   0   0   0   0   0    0    0    0   

           L13  L14  L15  
NOME                      
MARIA        0    0    0  
JOSE         0    0    0  
ANTONIO      0    0    0  
FRANCISCO    0    0    0  
JOAO         0    0    0

In [4]:
df2 = df.copy()
df2['TEMP'] = df2[['SEXO', 'QTDE']].apply(lambda x: [x[0]] * x[1], axis=1)
df3 = df2.explode('TEMP').drop(['TEMP', 'QTDE'], axis=1) #.reset_index()

# usar os dados expandidos invés dos agregados
df0 = df # guardar o dataframe original
df = df3 # apontar para o novo dataframe

In [5]:
X = df.drop(['SEXO'], axis=1) # tudo, exceto a coluna alvo
y = df['SEXO'] # apenas a coluna alvo
print('Forma dos dados originais:', X.shape, y.shape)

Forma dos dados originais: (47033, 16) (47033,)


In [6]:
# dividir dados em treino e teste

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

print("Shapes:", X_train.shape, X_test.shape, y_train.shape, y_test.shape)

Shapes: (31512, 16) (15521, 16) (31512,) (15521,)


In [7]:
# treinar com todos os dados disponíveis

X_train, y_train = X, y

print("Shapes:", X_train.shape, y_train.shape)

Shapes: (47033, 16) (47033,)


https://automl.github.io/auto-sklearn/master/manual.html

In [8]:
# https://automl.github.io/auto-sklearn/master/installation.html

#!curl -k https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install
#!pip3 install auto-sklearn

In [9]:
import autosklearn.classification

In [10]:
X_train.head()

L0  L1  L2  L3  L4  L5  L6  L7  L8  L9  L10  L11  L12  L13  L14  L15
NOME                                                                       
MARIA   1   9  18   1  13   0   0   0   0   0    0    0    0    0    0    0
MARIA   1   9  18   1  13   0   0   0   0   0    0    0    0    0    0    0
MARIA   1   9  18   1  13   0   0   0   0   0    0    0    0    0    0    0
MARIA   1   9  18   1  13   0   0   0   0   0    0    0    0    0    0    0
MARIA   1   9  18   1  13   0   0   0   0   0    0    0    0    0    0    0

In [11]:
y_train[:10]

NOME
MARIA    0
MARIA    0
MARIA    0
MARIA    0
MARIA    0
MARIA    0
MARIA    0
MARIA    0
MARIA    0
MARIA    0
Name: SEXO, dtype: uint8

In [12]:
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=20*60,
    per_run_time_limit=2*60,
    n_jobs=-1,
    memory_limit=2048,
    seed=42,
    include_preprocessors=["no_preprocessing"]
)
automl.fit(X_train, y_train)

AutoSklearnClassifier(include_preprocessors=['no_preprocessing'],
                      memory_limit=2048, n_jobs=-1, per_run_time_limit=120,
                      seed=42, time_left_for_this_task=1200)

In [13]:
print(automl.show_models())

[(0.100000, SimpleClassificationPipeline({'balancing:strategy': 'weighting', 'classifier:__choice__': 'adaboost', 'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'no_encoding', 'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'minority_coalescer', 'data_preprocessing:numerical_transformer:imputation:strategy': 'mean', 'data_preprocessing:numerical_transformer:rescaling:__choice__': 'robust_scaler', 'feature_preprocessor:__choice__': 'no_preprocessing', 'classifier:adaboost:algorithm': 'SAMME', 'classifier:adaboost:learning_rate': 0.4057619179361446, 'classifier:adaboost:max_depth': 6, 'classifier:adaboost:n_estimators': 138, 'data_preprocessing:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction': 0.16209406548980398, 'data_preprocessing:numerical_transformer:rescaling:robust_scaler:q_max': 0.9604424192244272, 'data_preprocessing:numerical_transformer:rescaling:robust_scaler:q_min': 0.01083785191812

In [14]:
print(automl.sprint_statistics())

auto-sklearn results:
  Dataset name: 8eee4e7e-c008-11eb-a8e4-f9537db820a8
  Metric: accuracy
  Best validation score: 0.999162
  Number of target algorithm runs: 291
  Number of successful target algorithm runs: 219
  Number of crashed target algorithm runs: 43
  Number of target algorithms that exceeded the time limit: 29
  Number of target algorithms that exceeded the memory limit: 0



In [15]:
losses_and_configurations = [
    (run_value.cost, run_key.config_id)
    for run_key, run_value in automl.automl_.runhistory_.data.items()
]
losses_and_configurations.sort()
print("Lowest loss:", losses_and_configurations[0][0])
print("Best configuration:", automl.automl_.runhistory_.ids_config[losses_and_configurations[0][1]])

Lowest loss: 0.0008375748985245401
Best configuration: Configuration:
  balancing:strategy, Value: 'weighting'
  classifier:__choice__, Value: 'adaboost'
  classifier:adaboost:algorithm, Value: 'SAMME'
  classifier:adaboost:learning_rate, Value: 0.5920220846817715
  classifier:adaboost:max_depth, Value: 10
  classifier:adaboost:n_estimators, Value: 76
  data_preprocessing:categorical_transformer:categorical_encoding:__choice__, Value: 'one_hot_encoding'
  data_preprocessing:categorical_transformer:category_coalescence:__choice__, Value: 'no_coalescense'
  data_preprocessing:numerical_transformer:imputation:strategy, Value: 'median'
  data_preprocessing:numerical_transformer:rescaling:__choice__, Value: 'minmax'
  feature_preprocessor:__choice__, Value: 'no_preprocessing'



In [16]:
# treinar o melhor modelo com todos os dados
automl.fit(X, y)

ValueError: {filepath} already exist. Different seeds should be provided for different jobs.

In [58]:
# carregar dados de teste: definir arquivo Pickle de entrada
#arquivo = 'afastamentos-nomes-sexo-preparado.pkl.bz2'
arquivo = 'cadastro-nomes-sexo-preparado.pkl.bz2'
#arquivo = 'extra/nome_sexo_pf05.csv'

In [21]:
df2 = pd.read_pickle(arquivo)
df2.head()

SEXO  L0  L1  L2  L3  L4  L5  L6  L7  L8  L9  L10  L11  L12  L13  L14  \
PNOME                                                                           
MARIA      0   1   9  18   1  13   0   0   0   0   0    0    0    0    0    0   
JOSE       1   5  19  15  10   0   0   0   0   0   0    0    0    0    0    0   
ANA        0   1  14   1   0   0   0   0   0   0   0    0    0    0    0    0   
JOAO       1  15   1  15  10   0   0   0   0   0   0    0    0    0    0    0   
CARLOS     1  19  15  12  18   1   3   0   0   0   0    0    0    0    0    0   

        L15  
PNOME        
MARIA     0  
JOSE      0  
ANA       0  
JOAO      0  
CARLOS    0

In [22]:
df2.shape

(48970, 17)

In [23]:
X_test = df2.drop(['SEXO'], axis=1) # tudo, exceto a coluna alvo
y_test = df2['SEXO'] # apenas a coluna alvo

In [24]:
y_pred = automl.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 1, 0], dtype=uint8)

In [25]:
from sklearn.metrics import accuracy_score

print("Accuracy score: %.2f %%" % (accuracy_score(y_test, y_pred) * 100))

Accuracy score: 96.71 %


In [26]:
from sklearn.metrics import confusion_matrix

print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Confusion matrix:
 [[21543   116   232]
 [   52 19024   183]
 [  471   558  6791]]
